name: Daily Dome Crawler

on:
  schedule:
    - cron: '15 15 * * *' # 한국 시간 자정 15분 (UTC 15:15)
  workflow_dispatch: # 내가 원할 때 수동으로 실행하는 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 내 코드 가져오기

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt # 도구 설치

      - name: Run Crawler
        run: python main.py # 크롤링 실행

      - name: Commit and Push
        run: |
          git config --global user.name "DomeBot"
          git config --global user.email "bot@github.com"
          git add data/*.json data/index.json
          git commit -m "Update daily data: $(date +'%Y-%m-%d')" || exit 0
          git push
